BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE USER_AUTHS
    (
        USER_AUTH_ID    NUMBER(19, 0) GENERATED AS IDENTITY PRIMARY KEY,
        USER_ID         NUMBER(19, 0)                        NOT NULL,
        AUTH_PROVIDER   VARCHAR2(20)                        NOT NULL,
        AUTH_ID         VARCHAR2(255)                       NOT NULL,
        CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        CONSTRAINT UK_USERS_AUTH_PROVIDER_AUTH_ID UNIQUE (AUTH_PROVIDER, AUTH_ID)
    )';

    EXECUTE IMMEDIATE 'COMMENT ON COLUMN USER_AUTHS.USER_ID IS ''유저 ID''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN USER_AUTHS.AUTH_PROVIDER IS ''인증 공급자''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN USER_AUTHS.AUTH_ID IS ''인증 공급자에서의 사용자 고유 ID''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN USER_AUTHS.CREATED_AT IS ''유저 최초 생성 시간''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN USER_AUTHS.UPDATED_AT IS ''유저 마지막 업데이트 시간''';
END;