BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE USERS
    (
        USER_ID         NUMBER(19, 0) GENERATED AS IDENTITY PRIMARY KEY,
        USER_NICKNAME   VARCHAR2(30)                        NOT NULL,
        ACTIVE          NUMBER(1)                           NOT NULL,
        CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        UPDATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        CONSTRAINT UK_USERS_USER_NICKNAME UNIQUE (USER_NICKNAME)
    )';

    EXECUTE IMMEDIATE 'COMMENT ON COLUMN USERS.USER_NICKNAME IS ''유저 닉네임''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN USERS.ACTIVE IS ''활성화 여부''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN USERS.CREATED_AT IS ''유저 최초 생성 시간''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN USERS.UPDATED_AT IS ''유저 마지막 업데이트 시간''';
END;